version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:12.18.3
    steps:
      - checkout
      - run: echo "Trying to install all dependences"
      - run: yarn
  test:
    steps:
      - checkout
      - run: echo "Trying to pass the tests"
      - run: yarn test
workflows:
  node-tests:
    jobs:
      - build
      - test
